#!/usr/bin/env bash

set -eu

outdir="output/canu"
if [[ ! -e "${outdir}" ]]; then
    mkdir -p "${outdir}"
fi

lr1="output/filtered_long_reads/asw12_20170627.fq.gz"
lr2="output/filtered_long_reads/asw_14_precipitation.fq.gz"
log_file="${outdir}/canu.log"

bin/canu/canu \
    -p long_read -d "${outdir}" \
    genomeSize=600m \
    -nanopore-raw "${lr1},${lr2}" \
    &> "${log_file}"
