#!/usr/bin/env bash

set -eu

export outdir
outdir="output/filtered_long_reads"
if [[ ! -e "${outdir}" ]]; then
    mkdir -p "${outdir}"
fi

filter_long_reads() {
    local _lr
    local _outfile
    local _outpath
    local cmd
    local cmd_log

    _lr="$(readlink -f "${1}")"

    printf "Processing long read file:\t%s\n" "${_lr}"

    if [[ "${_lr}" =~ ^(.*)(asw[^/]+)(.*)$ ]]; then
        _outfile="${BASH_REMATCH[2]}"
        _outpath="${outdir}/${_outfile}.fq.gz"
        printf "_outpath:\t%s\n" "${_outpath}"
    else
        exit 1
    fi

    cmd=( bin/bbmap/reformat.sh
            "in=${_lr}"
            "out=${_outpath}"
            minlength=1000
            minavgquality=10
            mingc=0.2
            maxgc=0.4
            "bhist=${outdir}/${_outfile}_bhist.txt"
            "qhist=${outdir}/${_outfile}_qhist.txt"
            "qchist=${outdir}/${_outfile}_qchist.txt"
            "aqhist=${outdir}/${_outfile}_aqhist.txt"
            "bqhist=${outdir}/${_outfile}_bqhist.txt"
            "lhist=${outdir}/${_outfile}_lhist.txt"
            "gchist=${outdir}/${_outfile}_gchist.txt"
            "ehist=${outdir}/${_outfile}_ehist.txt"
            "qahist=${outdir}/${_outfile}_qahist.txt"
            "indelhist=${outdir}/${_outfile}_indelhist.txt"
            "mhist=${outdir}/${_outfile}_mhist.txt"
            "idhist=${outdir}/${_outfile}_idhist.txt"
            idbins=auto gcbins=auto )

    cmd_log="${outdir}/${_outfile}.log"

    shopt -s extglob
    printf "Running command:\n"
    printf "%s " "${cmd[@]//+([[:blank:]])/ }"
    printf "\n"
    shopt -u extglob

    "${cmd[@]}" 2> "${cmd_log}" 
}

export -f filter_long_reads

find data/long_reads/ -name "*.fq.gz" \
    -exec bash -c 'filter_long_reads "${0}"' {} \;
