#!/usr/bin/env bash



cmd=( dipspades.py
        --threads 100
        --memory 900
        -o "${outdir}"
        --pe1-12 "${pe150}"
        --pe2-12 "${pe100}"
        --mp1-12 "${mp}"
        --mp1-rf
        --nanopore "${nanopore_corrected}"
        --trusted-contigs "${dd_isotigs}"
        --untrusted-contigs "${canu_contigs}"
        --hap "${haplotig_1}"
        --hap "${haplotig_2}"



 )


# haplocontigs: meraculous haplotigs

# trusted contigs: meraculous full-depth isotigs

# what about meraculous SD-isotigs?

# untrusted contigs: canu contigs

# nanopore-raw: canu corrected reads
