#!/usr/bin/env bash

set -eu

outdir="output/dipspades"
if [[ ! -e "${outdir}" ]]; then
    mkdir -p "${outdir}"
fi

# files
# what about meraculous SD-isotigs?
pe150="data/short_reads/pe150_filtered_trimmed.fastq.gz"
pe100="data/short_reads/pe100_filtered_trimmed.fastq.gz"
mp="data/mate_pairs/lmp.fastq.gz"
nanopore_corrected="output/canu/long_read.correctedReads.fasta.gz"
dd_isotigs="output/meraculous_haplotigs/dd_isotigs.fa"
canu_contigs="output/canu/long_read.contigs.fasta"
all_haplotigs="output/meraculous_haplotigs/all_haplotigs.fa"

cmd=( dipspades.py
        --threads 100
        --memory 900
        -o "${outdir}"
        --pe1-12 "${pe150}"
        --pe2-12 "${pe100}"
        --mp1-12 "${mp}"
        --mp1-rf
        --nanopore "${nanopore_corrected}"
        --trusted-contigs "${dd_isotigs}"
        --untrusted-contigs "${canu_contigs}"
        --hap "${all_haplotigs}" )


cmd_log="${outdir}/dipspades.log"

shopt -s extglob
printf "Running command:\n"
printf "%s " "${cmd[@]//+([[:blank:]])/ }"
printf "\n"
shopt -u extglob

"${cmd[@]}" &> "${cmd_log}" 